using System;
using System.Collections.Generic;
using UnityEngine;
using ERO.Core;
using ERO.Data;
using ERO.Art;
using ERO.Systems;

namespace ERO.World
{
    /// <summary>Playable vertical slice using the real ERO systems and procedural Aetheria art foundation.</summary>
    public sealed class EROPlayableVerticalSlice : MonoBehaviour
    {
        private const int ChunkSize = 48;
        private const int StreamRadius = 2;
        private const float PlayerSpeed = 7f;
        private const float SprintMultiplier = 1.65f;
        private const float MouseSensitivity = 2.2f;
        private readonly Dictionary<Vector2Int, GameObject> chunks = new Dictionary<Vector2Int, GameObject>();
        private readonly EROClass[] launchClasses =
        {
            EROClass.Paladin, EROClass.Priest, EROClass.Invocateur, EROClass.Mage,
            EROClass.Assassin, EROClass.Archer, EROClass.Guerrier
        };
        private CharacterController controller;
        private Transform player;
        private Camera playerCamera;
        private Transform enemy;
        private float pitch;
        private float enemyRespawnAt;
        private int enemyHealth;
        private int enemyMaxHealth;
        private float lastUpdateTime;
        private readonly EROSkillRuntimeState skillState = new EROSkillRuntimeState();
        private string status = "Welcome to Eternal Realms Online";
        private GUIStyle titleStyle;
        private GUIStyle panelStyle;
        private GUIStyle textStyle;

        private void Start(){EnsureCharacter();CreatePlayer();CreateLighting();UpdateStreaming();CreateEnemy();InitializeSkillRuntime();LockCursor(true);}
        private void Update(){if(player==null)return;HandleLook();HandleMovement();HandleClassSelection();RegenerateResource();HandleSkillInput();UpdateStreaming();UpdateEnemy();if(Input.GetKeyDown(KeyCode.Escape))LockCursor(Cursor.lockState!=CursorLockMode.Locked);if(Input.GetMouseButtonDown(0)||Input.GetKeyDown(KeyCode.Space))Attack();}
        private void EnsureCharacter(){var root=EROGameRoot.Instance;if(root!=null&&root.Systems!=null&&root.Systems.Character.Active==null)root.Systems.Character.NewCharacter("Aetherian",EROClass.Mage,Gender.Male);}
        private void CreatePlayer(){var go=new GameObject("ERO_Player");player=go.transform;player.position=new Vector3(0f,2f,0f);controller=go.AddComponent<CharacterController>();controller.height=1.8f;controller.radius=.35f;controller.center=new Vector3(0f,.9f,0f);controller.stepOffset=.35f;controller.slopeLimit=45f;var body=new GameObject("Aetherian_PlayerVisual");body.transform.SetParent(player);body.transform.localPosition=new Vector3(0f,.9f,0f);body.transform.localScale=new Vector3(.7f,.9f,.7f);var bodyRenderer=body.AddComponent<MeshRenderer>();var bodyFilter=body.AddComponent<MeshFilter>();bodyFilter.sharedMesh=BuildPlayerMesh();bodyRenderer.sharedMaterial=MakeMaterial(new Color(.16f,.28f,.72f));var cameraGo=new GameObject("ERO_PlayerCamera");cameraGo.transform.SetParent(player);cameraGo.transform.localPosition=new Vector3(0f,1.55f,0f);playerCamera=cameraGo.AddComponent<Camera>();playerCamera.fieldOfView=70f;playerCamera.nearClipPlane=.05f;playerCamera.farClipPlane=700f;}
        private void CreateLighting(){var lightGo=new GameObject("ERO_Aetheria_Sun");var light=lightGo.AddComponent<Light>();light.type=LightType.Directional;light.intensity=1.15f;light.transform.rotation=Quaternion.Euler(48f,-35f,0f);RenderSettings.ambientIntensity=.75f;RenderSettings.fog=true;RenderSettings.fogColor=new Color(.025f,.04f,.08f);RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=.0038f;}
        private void HandleLook(){if(Cursor.lockState!=CursorLockMode.Locked)return;player.Rotate(0f,Input.GetAxis("Mouse X")*MouseSensitivity,0f);pitch=Mathf.Clamp(pitch-Input.GetAxis("Mouse Y")*MouseSensitivity,-70f,70f);playerCamera.transform.localRotation=Quaternion.Euler(pitch,0f,0f);}
        private void HandleMovement(){if(Cursor.lockState!=CursorLockMode.Locked)return;float x=Input.GetAxisRaw("Horizontal"),z=Input.GetAxisRaw("Vertical");Vector3 direction=(player.right*x+player.forward*z).normalized;float speed=Input.GetKey(KeyCode.LeftShift)?PlayerSpeed*SprintMultiplier:PlayerSpeed;Vector3 velocity=direction*speed;velocity.y=controller.isGrounded?-1f:Physics.gravity.y;controller.Move(velocity*Time.deltaTime);}
        private void HandleClassSelection(){if(Cursor.lockState!=CursorLockMode.Locked)return;for(int i=0;i<launchClasses.Length;i++){if(!Input.GetKeyDown(KeyCode.Alpha1+i))continue;var root=EROGameRoot.Instance;if(root==null||root.Systems==null||root.Systems.Character.Active==null)return;var character=root.Systems.Character.Active;character.classId=launchClasses[i];InitializeSkillRuntime();status="Class selected • "+character.classId;return;}}
        private void InitializeSkillRuntime(){var root=EROGameRoot.Instance;if(root==null||root.Systems==null||root.Systems.Character.Active==null)return;EROSkillRuntimeSystem.Initialize(root.Systems.Character.Active,skillState);lastUpdateTime=Time.time;}
        private void RegenerateResource(){var now=Time.time;if(lastUpdateTime<=0f)lastUpdateTime=now;long elapsed=(long)Mathf.Max(0f,(now-lastUpdateTime)*1000f);if(elapsed>0)EROSkillRuntimeSystem.Regenerate(null,skillState,elapsed);lastUpdateTime=now;}
        private void HandleSkillInput(){if(Cursor.lockState!=CursorLockMode.Locked||enemy==null||enemyHealth<=0)return;var root=EROGameRoot.Instance;if(root==null||root.Systems==null||root.Systems.Character.Active==null)return;var character=root.Systems.Character.Active;var abilities=EROAbilitySystem.GetAbilities(character.classId,EROSpecialization.None,Mathf.Max(1,character.level));if(abilities.Count==0)return;int slot=-1;if(Input.GetKeyDown(KeyCode.Alpha8))slot=0;else if(Input.GetKeyDown(KeyCode.Alpha9))slot=1;else if(Input.GetKeyDown(KeyCode.Alpha0))slot=2;if(slot<0||slot>=abilities.Count)return;var ability=abilities[slot];Vector3 toEnemy=enemy.position-playerCamera.transform.position;if(toEnemy.magnitude>18f||Vector3.Angle(playerCamera.transform.forward,toEnemy)>30f){status="Skill target out of range";return;}var targetStats=EROCombatSystem.BuildStats(character);long now=(long)(Time.time*1000f);var result=EROSkillRuntimeSystem.TryCast(character,skillState,EROSpecialization.None,ability.id,targetStats,now,UnityEngine.Random.Range(0,10000),UnityEngine.Random.Range(0,10000),10000);if(!result.success){status=result.reason;return;}if(result.combat.result==EROCombatResultKind.Miss){status=ability.name+" missed";return;}int damage=Mathf.Max(1,(int)Mathf.Min((long)int.MaxValue,result.combat.mitigatedDamage));enemyHealth=Mathf.Max(0,enemyHealth-damage);status=ability.name+" • "+damage+" damage • "+skillState.currentResource+" resource";if(enemyHealth==0)DefeatEnemy(character);}
        private void UpdateStreaming(){Vector2Int center=WorldToChunk(player.position);var needed=new HashSet<Vector2Int>();for(int z=-StreamRadius;z<=StreamRadius;z++)for(int x=-StreamRadius;x<=StreamRadius;x++){var coord=new Vector2Int(center.x+x,center.y+z);needed.Add(coord);if(!chunks.ContainsKey(coord))chunks.Add(coord,GenerateChunk(coord));}var remove=new List<Vector2Int>();foreach(var pair in chunks)if(!needed.Contains(pair.Key))remove.Add(pair.Key);foreach(var coord in remove){if(chunks[coord]!=null)Destroy(chunks[coord]);chunks.Remove(coord);}}
        private GameObject GenerateChunk(Vector2Int coord){var root=new GameObject("Aetheria_Chunk_"+coord.x+"_"+coord.y);root.transform.position=new Vector3(coord.x*ChunkSize,0f,coord.y*ChunkSize);int seed=coord.x*73856093^coord.y*19349663;EROProceduralFantasyArt.CreateGround(root.transform,ChunkSize,seed);var random=new System.Random(seed);for(int i=0;i<14;i++){float x=(float)random.NextDouble()*(ChunkSize-6f)-(ChunkSize*.5f-3f);float z=(float)random.NextDouble()*(ChunkSize-6f)-(ChunkSize*.5f-3f);float scale=.65f+(float)random.NextDouble()*.75f;EROProceduralFantasyArt.CreateTree(root.transform,new Vector3(x,0f,z),scale,seed+i);}for(int i=0;i<3;i++){float x=(float)random.NextDouble()*(ChunkSize-8f)-(ChunkSize*.5f-4f);float z=(float)random.NextDouble()*(ChunkSize-8f)-(ChunkSize*.5f-4f);EROProceduralFantasyArt.CreateCrystal(root.transform,new Vector3(x,0f,z),.55f+(float)random.NextDouble()*.45f,seed+i*17);}return root;}
        private void CreateEnemy(){enemy=EROProceduralFantasyArt.CreateEnemy(null,new Vector3(0f,.2f,12f)).transform;enemyMaxHealth=100;enemyHealth=enemyMaxHealth;}
        private void UpdateEnemy(){if(enemy==null||player==null)return;if(enemyHealth<=0&&Time.time>=enemyRespawnAt){enemyHealth=enemyMaxHealth;enemy.gameObject.SetActive(true);enemy.position=player.position+player.forward*10f+Vector3.up*.2f;}if(enemyHealth>0){Vector3 flat=player.position-enemy.position;flat.y=0f;if(flat.sqrMagnitude>.01f)enemy.rotation=Quaternion.LookRotation(flat.normalized);}}
        private void Attack(){if(Cursor.lockState!=CursorLockMode.Locked||enemy==null||enemyHealth<=0)return;Vector3 toEnemy=enemy.position-playerCamera.transform.position;if(toEnemy.magnitude>16f||Vector3.Angle(playerCamera.transform.forward,toEnemy)>24f)return;var root=EROGameRoot.Instance;if(root==null||root.Systems==null||root.Systems.Character.Active==null)return;var character=root.Systems.Character.Active;var stats=EROCombatSystem.BuildStats(character);var skill=new EROSkillDefinition{id="basic_attack",classId=character.classId,damageType=(character.classId==EROClass.Mage||character.classId==EROClass.Priest||character.classId==EROClass.Invocateur)?ERODamageType.Magical:ERODamageType.Physical,requiredLevel=1,powerBasisPoints=10000,criticalBonusBasisPoints=0,accuracyBonusBasisPoints=0,cooldownMilliseconds=500,resourceCost=0,areaOfEffect=false};var combatEvent=EROCombatSystem.ResolveAttack(stats,stats,skill,0,UnityEngine.Random.Range(0,10000),10000);if(combatEvent.result==EROCombatResultKind.Miss){status="Attack missed";return;}int damage=Mathf.Max(1,(int)Mathf.Min((long)int.MaxValue,combatEvent.mitigatedDamage));enemyHealth=Mathf.Max(0,enemyHealth-damage);status=(combatEvent.critical?"Critical! ":"Hit for ")+damage+" damage";if(enemyHealth==0)DefeatEnemy(character);}
        private void DefeatEnemy(CharacterData character){var root=EROGameRoot.Instance;if(root==null||root.Systems==null)return;enemy.gameObject.SetActive(false);enemyRespawnAt=Time.time+3f;root.Systems.Progression.AddXP(character,150);character.credits+=25;AddLoot(character,"loot_ember_shard","Ember Shard");status="Enemy defeated • +150 XP • +25 Credits";}
        private static void AddLoot(CharacterData character,string id,string name){if(character.inventory==null)character.inventory=new List<ItemData>();foreach(var item in character.inventory)if(item!=null&&item.id==id&&!item.equipped){item.quantity++;return;}character.inventory.Add(new ItemData{id=id,name=name,rarity=Rarity.Uncommon,level=1,quantity=1});}
        private void OnGUI(){titleStyle??=new GUIStyle(GUI.skin.label){fontSize=22,fontStyle=FontStyle.Bold};panelStyle??=new GUIStyle(GUI.skin.box){alignment=TextAnchor.UpperLeft,fontSize=14};textStyle??=new GUIStyle(GUI.skin.label){fontSize=14};var root=EROGameRoot.Instance;var character=root!=null&&root.Systems!=null?root.Systems.Character.Active:null;if(character==null)return;GUI.Box(new Rect(18,18,430,260),GUIContent.none,panelStyle);GUI.Label(new Rect(32,28,390,30),"ETERNAL REALMS ONLINE",titleStyle);GUI.Label(new Rect(32,64,390,24),character.name+" • "+character.classId,textStyle);GUI.Label(new Rect(32,88,390,24),"Level "+character.level+"   XP "+character.xp+"   Credits "+character.credits,textStyle);GUI.Label(new Rect(32,112,390,24),"Inventory: "+(character.inventory==null?0:character.inventory.Count)+" stacks",textStyle);GUI.Label(new Rect(32,136,390,24),"WASD Move • Shift Sprint • Mouse Look",textStyle);GUI.Label(new Rect(32,160,390,24),"1-7: Paladin/Priest/Invocateur/Mage/Assassin/Archer/Guerrier",textStyle);GUI.Label(new Rect(32,184,390,24),"LMB / Space: Basic Attack",textStyle);GUI.Label(new Rect(32,208,390,24),"8/9/0: Class Skills • Resource "+skillState.currentResource+"/"+skillState.maximumResource,textStyle);GUI.Label(new Rect(32,232,390,24),status,textStyle);if(enemy!=null&&enemyHealth>0){GUI.Box(new Rect(Screen.width*.5f-140f,34,280,42),GUIContent.none,panelStyle);GUI.Label(new Rect(Screen.width*.5f-125f,42,250,24),"Aether Beast  "+enemyHealth+"/"+enemyMaxHealth,textStyle);}}
        private static Vector2Int WorldToChunk(Vector3 position)=>new Vector2Int(Mathf.FloorToInt(position.x/ChunkSize),Mathf.FloorToInt(position.z/ChunkSize));
        private static Material MakeMaterial(Color color){var shader=Shader.Find("Universal Render Pipeline/Lit")??Shader.Find("Standard");return new Material(shader){color=color};}
        private static Mesh BuildPlayerMesh(){var mesh=new Mesh{name="Aetherian_PlayerSilhouette"};mesh.vertices=new[]{new Vector3(0f,1f,0f),new Vector3(-.48f,0f,-.32f),new Vector3(.48f,0f,-.32f),new Vector3(.48f,0f,.32f),new Vector3(-.48f,0f,.32f),new Vector3(0f,1.8f,0f),new Vector3(-.28f,.9f,0f),new Vector3(.28f,.9f,0f)};mesh.triangles=new[]{0,1,2,0,2,3,0,3,4,0,4,1,5,2,1,5,3,2,5,4,3,5,1,4,6,7,5,7,6,0};mesh.RecalculateNormals();return mesh;}
        private static void LockCursor(bool locked){Cursor.lockState=locked?CursorLockMode.Locked:CursorLockMode.None;Cursor.visible=!locked;}
    }
}