using System.Collections.Generic;
using UnityEngine;
using ERO.Art;

namespace ERO.World
{
    /// <summary>
    /// Reusable deterministic chunk streamer. Only rebuilds the active window when the
    /// target crosses a chunk boundary. Chunk creation and destruction are budgeted across
    /// frames so crossing a boundary does not synchronously generate the entire window.
    /// </summary>
    public sealed class EROWorldChunkStreamer : MonoBehaviour
    {
        [SerializeField, Min(8)] private int chunkSize = 48;
        [SerializeField, Range(1, 8)] private int streamRadius = 2;
        [SerializeField, Min(1)] private int maxGeneratedChunksPerFrame = 2;
        [SerializeField, Min(1)] private int maxDestroyedChunksPerFrame = 2;
        [SerializeField] private Transform target;

        private readonly Dictionary<Vector2Int, GameObject> chunks = new Dictionary<Vector2Int, GameObject>();
        private readonly Queue<Vector2Int> generationQueue = new Queue<Vector2Int>();
        private readonly HashSet<Vector2Int> queuedGeneration = new HashSet<Vector2Int>();
        private Vector2Int streamedCenter = new Vector2Int(int.MinValue, int.MinValue);

        public int LoadedChunkCount => chunks.Count;
        public Vector2Int CurrentChunk => streamedCenter;

        private void Update()
        {
            if (target == null) return;

            var center = WorldToChunk(target.position);
            if (center != streamedCenter) UpdateStreaming(center);
            ProcessGenerationBudget();
        }

        public void SetTarget(Transform value)
        {
            target = value;
            streamedCenter = new Vector2Int(int.MinValue, int.MinValue);
            generationQueue.Clear();
            queuedGeneration.Clear();
        }

        public void Rebuild()
        {
            streamedCenter = new Vector2Int(int.MinValue, int.MinValue);
            generationQueue.Clear();
            queuedGeneration.Clear();
            if (target != null) UpdateStreaming(WorldToChunk(target.position));
        }

        private void UpdateStreaming(Vector2Int center)
        {
            streamedCenter = center;

            for (int z = -streamRadius; z <= streamRadius; z++)
            {
                for (int x = -streamRadius; x <= streamRadius; x++)
                {
                    var coord = new Vector2Int(center.x + x, center.y + z);
                    if (!chunks.ContainsKey(coord) && queuedGeneration.Add(coord))
                    {
                        generationQueue.Enqueue(coord);
                    }
                }
            }

            int destroyed = 0;
            var remove = new List<Vector2Int>();
            foreach (var pair in chunks)
            {
                if (destroyed + remove.Count >= maxDestroyedChunksPerFrame) break;
                if (!IsWithinStreamWindow(pair.Key, center)) remove.Add(pair.Key);
            }

            foreach (var coord in remove)
            {
                GameObject chunk;
                if (chunks.TryGetValue(coord, out chunk))
                {
                    DestroyGeneratedChunk(chunk);
                    chunks.Remove(coord);
                    destroyed++;
                }
            }
        }

        private void ProcessGenerationBudget()
        {
            int generated = 0;
            while (generated < maxGeneratedChunksPerFrame && generationQueue.Count > 0)
            {
                var coord = generationQueue.Dequeue();
                queuedGeneration.Remove(coord);

                // The player may have crossed another boundary while this coordinate was queued.
                // Stale work is discarded instead of creating chunks outside the active interest window.
                if (!IsWithinStreamWindow(coord, streamedCenter) || chunks.ContainsKey(coord)) continue;

                chunks.Add(coord, GenerateChunk(coord));
                generated++;
            }
        }

        private bool IsWithinStreamWindow(Vector2Int coord, Vector2Int center)
        {
            return Mathf.Abs(coord.x - center.x) <= streamRadius
                && Mathf.Abs(coord.y - center.y) <= streamRadius;
        }

        private GameObject GenerateChunk(Vector2Int coord)
        {
            var root = new GameObject($"Aetheria_Chunk_{coord.x}_{coord.y}");
            root.transform.SetParent(transform, false);
            root.transform.position = new Vector3(coord.x * chunkSize, 0f, coord.y * chunkSize);
            int seed = coord.x * 73856093 ^ coord.y * 19349663;
            EROProceduralFantasyArt.CreateGround(root.transform, chunkSize, seed);
            return root;
        }

        private static void DestroyGeneratedChunk(GameObject chunk)
        {
            if (chunk == null) return;

            // Every mesh/material below a streamed chunk is generated by EROProceduralFantasyArt.
            // Release those native Unity objects explicitly so repeated zone travel does not
            // accumulate memory on long-lived MMO client sessions.
            var meshes = new HashSet<Mesh>();
            var materials = new HashSet<Material>();
            var meshFilters = chunk.GetComponentsInChildren<MeshFilter>(true);
            foreach (var filter in meshFilters)
            {
                if (filter.sharedMesh != null) meshes.Add(filter.sharedMesh);
            }

            var colliders = chunk.GetComponentsInChildren<MeshCollider>(true);
            foreach (var collider in colliders)
            {
                if (collider.sharedMesh != null) meshes.Add(collider.sharedMesh);
            }

            var renderers = chunk.GetComponentsInChildren<Renderer>(true);
            foreach (var renderer in renderers)
            {
                if (renderer.sharedMaterial != null) materials.Add(renderer.sharedMaterial);
            }

            Object.Destroy(chunk);
            foreach (var material in materials) Object.Destroy(material);
            foreach (var mesh in meshes) Object.Destroy(mesh);
        }

        private Vector2Int WorldToChunk(Vector3 position)
        {
            return new Vector2Int(Mathf.FloorToInt(position.x / chunkSize), Mathf.FloorToInt(position.z / chunkSize));
        }

        private void OnDestroy()
        {
            foreach (var pair in chunks)
            {
                DestroyGeneratedChunk(pair.Value);
            }
            chunks.Clear();
            generationQueue.Clear();
            queuedGeneration.Clear();
        }
    }
}
