; ERO-Aetheria Unreal Engine baseline

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/EROAetheria")

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
EditorStartupMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/EROAetheria.EROGameMode

[/Script/Engine.NetworkSettings]
n.VerifyPeer=0

[SystemSettings]
net.MaxRPCPerNetUpdate=8
