; ERO-Aetheria Unreal Engine 5.8 visual baseline
; UE5-native visual authoring: Lumen + Nanite + World Partition + PCG + Niagara.

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/EROAetheria")

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
EditorStartupMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/EROAetheria.EROGameMode

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.GenerateMeshDistanceFields=True
r.Nanite.ProjectEnabled=True
r.VirtualTextures=True
r.VirtualTexturedLightmaps=True
r.Lumen.HardwareRayTracing=0
r.Shadow.Virtual.Enable=1
r.AllowStaticLighting=False

[/Script/Engine.NetworkSettings]
n.VerifyPeer=0

[SystemSettings]
net.MaxRPCPerNetUpdate=8
